export const letterData = [
    { letter: "a", frequency: 0.08167 },
    { letter: "b", frequency: 0.01492 },
    { letter: "c", frequency: 0.02782 },
    { letter: "d", frequency: 0.04253 },
    { letter: "e", frequency: 0.12702 },
    { letter: "f", frequency: 0.02228 },
    { letter: "g", frequency: 0.02015 },
    { letter: "h", frequency: 0.06094 },
    { letter: "i", frequency: 0.06966 },
    { letter: "j", frequency: 0.00153 },
    { letter: "k", frequency: 0.00772 },
    { letter: "l", frequency: 0.04025 },
    { letter: "m", frequency: 0.02406 },
    { letter: "n", frequency: 0.06749 },
    { letter: "o", frequency: 0.07507 },
    { letter: "p", frequency: 0.01929 },
    { letter: "q", frequency: 0.00095 },
    { letter: "r", frequency: 0.05987 },
    { letter: "s", frequency: 0.06327 },
    { letter: "t", frequency: 0.09056 },
    { letter: "u", frequency: 0.02758 },
    { letter: "v", frequency: 0.00978 },
    { letter: "w", frequency: 0.0236 },
    { letter: "x", frequency: 0.0015 },
    { letter: "y", frequency: 0.01974 },
    { letter: "z", frequency: 0.00074 }
  ];

  export const riverNodesData = [
    {id: "freshwater river", name: "Freshwater River", group: "river", layer: 6},
    {id: "geothermally heated river", name: "Geothermal Heated River", group: "river", layer: 6},
    {id: "underground river", name: "Underground River", group: "river", layer: 4},
    {id: "tidal creek", name: "Tidal Creek", group: "creek", layer: 5},
    {id: "river", name: "River", group: "river", layer: 5},
    {id: "underground stream", name: "Underground Stream", group: "stream", layer: 3},
    {id: "tidal watercourse", name: "Tidal Watercourse", group: "watercourse", layer: 4},
    {id: "stream", name: "Stream", group: "stream", layer: 4},
    {id: "hypoxic lake", name: "Hypoxic Lake", group: "lake", layer: 4},
    {id: "watercourse", name: "Watercourse", group: "watercourse", layer: 3},
    {id: "lake", name: "Lake", group: "lake", layer: 3},
    {id: "lotic water body", name: "Lotic Water Body", group: "water body", layer: 2},
    {id: "lentic water body", name: "Lentic Water Body", group: "water body", layer: 2},
    {id: "underground water body", name: "Underground Water Body", group: "water body", layer: 2},
    {id: "water body", name: "Water Body", group: "water body", layer: 1}
  ]
  export const riverLinksData = [
    ["freshwater river","river"],
    ["geothermally heated river","river"],
    ["underground river","underground stream"],
    ["underground river","river"],
    ["tidal creek","tidal watercourse"],
    ["river","stream"],
    ["underground stream","stream"],
    ["underground stream","underground water body"],
    ["tidal watercourse","watercourse"],
    ["stream","watercourse"],
    ["hypoxic lake","lake"],
    ["watercourse","lotic water body"],
    ["lake","lentic water body"],
    ["lotic water body","water body"],
    ["underground water body","water body"],
    ["lentic water body","water body"]
]